spring:
  application:
    name: monitoring

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

#  hikari pool status check
#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE


